[project]
name = "kimi-exp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.1",
    "huggingface-hub>=1.1.4",
    "safetensors>=0.7.0",
    "tabulate>=0.9.0",
    "torch>=2.9.1",
    "triton>=3.5.1",
]
